name: Update Links
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  update_links:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run script
      run: node .github/scripts/update_links.js
    - name: Commit and push changes
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actor
        message: "Update links"
        add: .
